env: standard
runtime: nodejs10
service: default

handlers:
  - url: /static
    static_dir: dist/static

  - url: /(.*\.(json|ico|js|css))$
    static_files: dist/\1
    upload: dist/.*\.(json|ico|js|css)$
    
  - url: /(.+\.(gif|png|jpg))$
    static_files: \1
    upload: .+\.(gif|png|jpg)$

  - url: /.*
    static_files: dist/index.html
    upload: dist/index.html
