runtime: nodejs10
handlers:
  - url: /js/(.*)
    static_files: dist/js/\1
    upload: dist/js/(.*)
  - url: /css/(.*)
    static_files: dist/css/\1
    upload: dist/css/(.*)
  - url: /images/(.*)
    static_files: dist/images/\1
    upload: dist/images/(.*)
  - url: /(.*\.(json|ico))$
    static_files: dist/\1
    upload: dist/.*\.(json|ico)$
  - url: /
    static_files: dist/index.html
    upload: dist/index.html
  - url: /.*
    static_files: dist/index.html
    upload: dist/index.html
